# Generated by Django 5.2.6 on 2025-09-25 17:48

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="batch_code",
            field=models.CharField(
                blank=True, help_text="Cohort identifier (e.g., b29).", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Full name as it should appear on result slips.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="recovery_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional personal email for roster recovery communications.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_number",
            field=models.CharField(
                blank=True,
                help_text="Unique roll number assigned by the institution.",
                max_length=32,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Roll numbers may only contain letters, numbers, dashes or underscores.",
                        regex="^[A-Za-z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Whether the student account is active on the portal.",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["roll_number"], name="student_roll_number_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="student_status_idx"),
        ),
    ]
