# Generated by Django 5.2.6 on 2025-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_batch_code_student_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the student record.', max_length=10),
        ),
    ]
