# Generated by Django 5.2.7 on 2025-10-25 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Label for the year/class (e.g., '1st Year', 'Final Year')", max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(help_text='Numeric order for sorting (1, 2, 3, etc.)', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Year/Class',
                'verbose_name_plural': 'Year/Classes',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for student access verification.', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Current status of the student record.', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique access code', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was first used', null=True)),
                ('student', models.ForeignKey(help_text='Student this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='accounts.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='year_class',
            field=models.ForeignKey(blank=True, help_text='Academic year/class for this student', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='accounts.yearclass'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number__isnull', False), ('year_class__isnull', False)), fields=('year_class', 'roll_number'), name='unique_year_class_roll_number'),
        ),
        migrations.AddIndex(
            model_name='studentaccesstoken',
            index=models.Index(fields=['code'], name='access_token_code_idx'),
        ),
        migrations.AddIndex(
            model_name='studentaccesstoken',
            index=models.Index(fields=['expires_at'], name='access_token_expires_idx'),
        ),
    ]
