# Generated by Django 5.2.7 on 2025-10-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_student_status"),
        ("accounts", "0005_yearclass_student_phone_alter_student_status_and_more"),
    ]

    operations = []
