# Generated by Django 5.2.7 on 2025-10-25 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_yearclass_student_phone_alter_student_status_and_more'),
        ('results', '0003_importbatch_csv_filename_importbatch_errors_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('flag_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='results.exam')),
            ],
            options={
                'ordering': ('-detected_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_rate_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cohens_d', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_current', to='results.exam')),
                ('previous_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_as_previous', to='results.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('mean_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('std_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_a_count', models.PositiveIntegerField(default=0)),
                ('grade_b_count', models.PositiveIntegerField(default=0)),
                ('grade_c_count', models.PositiveIntegerField(default=0)),
                ('grade_d_count', models.PositiveIntegerField(default=0)),
                ('grade_f_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.OneToOneField(help_text='Exam these aggregates are for', on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='results.exam')),
            ],
            options={
                'ordering': ('-computed_at',),
            },
        ),
        migrations.CreateModel(
            name='TrendAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=100)),
                ('trend_data', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='accounts.yearclass')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('THEORY', 'Theory/Written'), ('PRACTICAL', 'Practical/Viva'), ('TOTAL', 'Total')], max_length=20)),
                ('mean_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('std_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_aggregates', to='results.exam')),
            ],
            options={
                'ordering': ('-computed_at', 'component'),
                'unique_together': {('exam', 'component')},
            },
        ),
    ]
